version: '3.10'
services:
  api-gateway:
    image: nginx:latest
    container_name: api_gateway
    restart: always
    ports:
      - protocol: tcp
        target: 80
        published: 8881
    environment:
      NGINX_PORT: 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - spring-network
    depends_on:
      - user-management-service
      - jwt-auth-service
      - eureka-server

  user-management-db:
    image: postgres:latest
    container_name: user-management-db
    restart: always
    environment:
      - POSTGRES_DB=user_management_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2165
      - POSTGRES_SCHEMA=users
    ports:
      - "5432:5432"
    command: [ "postgres", "-c", "search_path=users" ]
    networks:
      - spring-network

  jwt-auth-service:
    image: jwt_auth_service:latest
    container_name: jwt-auth-service
    build:
      context: ./jwt_auth_service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - eureka-server
      - user-management-db

  eureka-server:
    image: eureka_server:latest
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - spring-network

  user-management-service:
    image: user_management_service:latest
    build:
      context: ./user_management_service
      dockerfile: Dockerfile
    container_name: user-management-service
    ports:
      - "8081:8081"
    networks:
      - spring-network
    depends_on:
      - eureka-server
      - user-management-db

networks:
  spring-network:
    driver: bridge
