spring:
  cloud:
    gateway:
      routes:
        - id: user_management_service
          uri: lb://USER-MANAGEMENT-SERVICE
          predicates:
            - Path=/api/users/admin/**
          filters:
            - name: AuthenticationFilter
              args:
                roles: [ROLE_ADMIN]

        - id: jwt_auth_service
          uri: lb://JWT-AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
          filters:
            - name: AuthenticationFilter
              args:
                roles: [ROLE_ADMIN, ROLE_CASHIER, ROLE_STORE_MANAGER]

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**
          filters:
            - name: AuthenticationFilter
              args:
                roles: [ROLE_ADMIN, ROLE_CASHIER, ROLE_STORE_MANAGER]

        - id: sales-service
          uri: lb://SALES-SERVICE
          predicates:
            - Path=/api/cashier/**
          filters:
            - name: AuthenticationFilter
              args:
                roles: [ROLE_CASHIER]

        - id: reporting-service
          uri: lb://REPORTING-SERVICE
          predicates:
            - Path=/api/store-manager/**
          filters:
            - name: AuthenticationFilter
              args:
                roles: [ ROLE_STORE_MANAGER ]

  application:
    name: GATEWAY-SERVICE

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/