spring:
  cloud:
    gateway:
      routes:
        - id: user_management_service
          uri: lb://USER-MANAGEMENT-SERVICE
          predicates:
            - Path=/api/users/admin/**
          filters:
            - name: AuthenticationFilter
              args:
                roles: [ROLE_ADMIN]
            - name: CircuitBreaker
              args:
                name: USER-MANAGEMENT-SERVICE
                fallbackUri: forward:/userManagementServiceFallBack

        - id: jwt_auth_service
          uri: lb://JWT-AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
          filters:
            - name: AuthenticationFilter
              args:
                roles: [ROLE_ADMIN, ROLE_CASHIER, ROLE_STORE_MANAGER]
            - name: CircuitBreaker
              args:
                name: JWT-AUTH-SERVICE
                fallbackUri: forward:/jwtAuthServiceFallBack

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**
          filters:
            - name: AuthenticationFilter
              args:
                roles: [ROLE_ADMIN, ROLE_CASHIER, ROLE_STORE_MANAGER]
            - name: CircuitBreaker
              args:
                name: PRODUCT-SERVICE
                fallbackUri: forward:/productServiceFallBack

        - id: sales-service
          uri: lb://SALES-SERVICE
          predicates:
            - Path=/api/cashier/**
          filters:
            - name: AuthenticationFilter
              args:
                roles: [ROLE_CASHIER]
            - name: CircuitBreaker
              args:
                name: SALES-SERVICE
                fallbackUri: forward:/salesServiceFallBack

        - id: reporting-service
          uri: lb://REPORTING-SERVICE
          predicates:
            - Path=/api/reports/**
          filters:
            - name: AuthenticationFilter
              args:
                roles: [ ROLE_STORE_MANAGER ]
            - name: CircuitBreaker
              args:
                name: REPORTING-SERVICE
                fallbackUri: forward:/reportingServiceFallBack

  application:
    name: GATEWAY-SERVICE